/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LavoraConNoiRouteImport } from './routes/lavora-con-noi'
import { Route as CorsiRouteImport } from './routes/corsi'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CorsoReturnRouteImport } from './routes/corso.return'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LavoraConNoiRoute = LavoraConNoiRouteImport.update({
  id: '/lavora-con-noi',
  path: '/lavora-con-noi',
  getParentRoute: () => rootRouteImport,
} as any)
const CorsiRoute = CorsiRouteImport.update({
  id: '/corsi',
  path: '/corsi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CorsoReturnRoute = CorsoReturnRouteImport.update({
  id: '/corso/return',
  path: '/corso/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/corsi': typeof CorsiRoute
  '/lavora-con-noi': typeof LavoraConNoiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/corso/return': typeof CorsoReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/blog/': typeof BlogIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/corsi': typeof CorsiRoute
  '/lavora-con-noi': typeof LavoraConNoiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/corso/return': typeof CorsoReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/blog': typeof BlogIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/corsi': typeof CorsiRoute
  '/lavora-con-noi': typeof LavoraConNoiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/blog': typeof AdminBlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/corso/return': typeof CorsoReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/blog/': typeof BlogIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/corsi'
    | '/lavora-con-noi'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/blog'
    | '/blog/$slug'
    | '/corso/return'
    | '/email/unsubscribe'
    | '/blog/'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/corsi'
    | '/lavora-con-noi'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/blog'
    | '/blog/$slug'
    | '/corso/return'
    | '/email/unsubscribe'
    | '/blog'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/corsi'
    | '/lavora-con-noi'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/blog'
    | '/blog/$slug'
    | '/corso/return'
    | '/email/unsubscribe'
    | '/blog/'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  CorsiRoute: typeof CorsiRoute
  LavoraConNoiRoute: typeof LavoraConNoiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminBlogRoute: typeof AdminBlogRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CorsoReturnRoute: typeof CorsoReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lavora-con-noi': {
      id: '/lavora-con-noi'
      path: '/lavora-con-noi'
      fullPath: '/lavora-con-noi'
      preLoaderRoute: typeof LavoraConNoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corsi': {
      id: '/corsi'
      path: '/corsi'
      fullPath: '/corsi'
      preLoaderRoute: typeof CorsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corso/return': {
      id: '/corso/return'
      path: '/corso/return'
      fullPath: '/corso/return'
      preLoaderRoute: typeof CorsoReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  CorsiRoute: CorsiRoute,
  LavoraConNoiRoute: LavoraConNoiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminBlogRoute: AdminBlogRoute,
  BlogSlugRoute: BlogSlugRoute,
  CorsoReturnRoute: CorsoReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  BlogIndexRoute: BlogIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
